# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIKit Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIKit Example
  pod 'Pagecall', path: '../../'
  pod 'Pagecall/Log', path: '../../'
  pod 'WebRTC-SDK', git: 'https://github.com/pplink/webrtc-specs'
end
